// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQVLReFZZqrOgnWFJ7wGtAUtBvZ08dCrQ',
    appId: '1:806056650750:web:a1e3771c1db86d6ab502af',
    messagingSenderId: '806056650750',
    projectId: 'bizquizapp',
    authDomain: 'bizquizapp.firebaseapp.com',
    databaseURL: 'https://bizquizapp-default-rtdb.firebaseio.com',
    storageBucket: 'bizquizapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy7veRuSG8lzXn667_NWO6IxPARn-1jns',
    appId: '1:806056650750:android:c55653c02ec6052eb502af',
    messagingSenderId: '806056650750',
    projectId: 'bizquizapp',
    databaseURL: 'https://bizquizapp-default-rtdb.firebaseio.com',
    storageBucket: 'bizquizapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjI37udlWKdCADWpVPCJXm3USi32IAnuU',
    appId: '1:806056650750:ios:3859f31150d8af6fb502af',
    messagingSenderId: '806056650750',
    projectId: 'bizquizapp',
    databaseURL: 'https://bizquizapp-default-rtdb.firebaseio.com',
    storageBucket: 'bizquizapp.appspot.com',
    androidClientId: '806056650750-8jkp1k483fhjbooroi6barr9g4gkvf1j.apps.googleusercontent.com',
    iosClientId: '806056650750-686386hjavk25vrecfdkmo5p7f2drv2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjI37udlWKdCADWpVPCJXm3USi32IAnuU',
    appId: '1:806056650750:ios:23f17469eb8eaca0b502af',
    messagingSenderId: '806056650750',
    projectId: 'bizquizapp',
    databaseURL: 'https://bizquizapp-default-rtdb.firebaseio.com',
    storageBucket: 'bizquizapp.appspot.com',
    androidClientId: '806056650750-8jkp1k483fhjbooroi6barr9g4gkvf1j.apps.googleusercontent.com',
    iosClientId: '806056650750-37spc6aojmgsh7ldrl2cv5n5kp0cbqvi.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
